# Generated by Django 5.1.3 on 2024-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customuser_last_paid_customuser_last_paid_for_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cur_bill_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cur_bill_amount',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cur_bill_item',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cur_bill_type',
            field=models.TextField(default='NULL'),
        ),
    ]
