# Generated by Django 5.1.3 on 2024-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_bill_remove_customuser_cur_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
