# Generated by Django 5.1.3 on 2024-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_customuser_peak_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.TextField()),
                ('sent_by', models.TextField()),
                ('constructions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionBuyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.TextField()),
                ('sent_by', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='peak_balance',
            field=models.IntegerField(default=500),
        ),
    ]
