# Generated by Django 5.1.3 on 2024-12-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_hotelbuildrequest_regionbuyrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbuildrequest',
            old_name='constructions',
            new_name='count',
        ),
    ]
