# Generated by Django 5.1.3 on 2024-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_constructions_hotelbuildrequest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='regions_have',
            field=models.TextField(default='[]'),
        ),
    ]
