# Generated by Django 5.1.3 on 2024-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_customuser_regions_have'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRegionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField()),
                ('receiver', models.TextField()),
                ('approved_by_receiver', models.BooleanField()),
                ('region_name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
